{% set name = "types-futures" %}
{% set version = "3.3.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-futures-{{ version }}.tar.gz
  sha256: 6fe8ccc2c2af7ef2fdd9bf73eab6d617074f09f30ad7d373510b4043d39c42de

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python

test:
  commands:
    - test -f $SP_DIR/concurrent-python2-stubs/futures/__init__.pyi


about:
  home: https://github.com/python/typeshed
  dev_url: https://github.com/python/typeshed
  doc_url: https://typing.readthedocs.io/
  summary: Typing stubs for futures
  description: |
    This is a PEP 561 type stub package for the futures package. 
    It can be used by type-checking tools like mypy, PyCharm, 
    pytype etc. to check code that uses futures.
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  license_family: Apache

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
