{% set name = "types-futures" %}
{% set version = "3.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-futures-{{ version }}.tar.gz
  sha256: 1c1ea9af10e0c9cb957b9ac3310d108df9a886a72b5008a03ed61abe50373d4e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/concurrent-python2-stubs/futures/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for futures
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
